### ISSUE TITLE
Endless Loop during ScalaDoc generation

### ISSUE THREAD

**Issue by swachter** [scalameta/paradise#214] opened 2017-07-10 07:20 UTC
In a project involving macros there seems to be an endless loop when generating ScalaDoc. Taking 3 thread dumps always returned the following stack trace:

```
"pool-5-thread-1" #46 prio=5 os_prio=0 tid=0x00007f679513d000 nid=0x7943 runnable [0x00007f673a4f4000]
   java.lang.Thread.State: RUNNABLE
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.searchConcreteThenDeferred(FindMembers.scala:56)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.apply(FindMembers.scala:48)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1031)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1033)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:648)
	at scala.reflect.internal.Types$Type.member(Types.scala:615)
	at org.scalameta.paradise.typechecker.Namers$Namer.member$1(Namers.scala:535)
	at org.scalameta.paradise.typechecker.Namers$Namer.resolve$1(Namers.scala:553)
	at org.scalameta.paradise.typechecker.Namers$Namer.probeMacroAnnotation(Namers.scala:626)
	at org.scalameta.paradise.typechecker.Namers$Namer.probeMacroAnnotation$(Namers.scala:492)
	at org.scalameta.paradise.typechecker.Namers$$anon$3.probeMacroAnnotation(Namers.scala:12)
	at org.scalameta.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand$1(Namers.scala:388)
	at org.scalameta.paradise.typechecker.Namers$Namer$$anon$2.$anonfun$maybeExpand$5(Namers.scala:417)
	at org.scalameta.paradise.typechecker.Namers$Namer$$anon$2$$Lambda$3694/278080223.apply(Unknown Source)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:486)
	at org.scalameta.paradise.typechecker.Namers$Namer$$anon$2.maybeExpand(Namers.scala:417)
	at org.scalameta.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.completeImpl(Namers.scala:349)
	at org.scalameta.paradise.typechecker.Namers$Namer$MaybeExpandeeCompleter.complete(Namers.scala:339)
	at org.scalameta.paradise.typechecker.Namers$Namer$RichType.completeOnlyExpansions(Namers.scala:368)
	at org.scalameta.paradise.typechecker.Expanders$Expander.$anonfun$expandMacroAnnotations$2(Expanders.scala:304)
	at org.scalameta.paradise.typechecker.Expanders$Expander$$Lambda$3691/716653180.apply(Unknown Source)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at org.scalameta.paradise.typechecker.Expanders$Expander.expandMacroAnnotations(Expanders.scala:294)
	at org.scalameta.paradise.typechecker.Expanders$Expander.expandMacroAnnotations$(Expanders.scala:277)
	at org.scalameta.paradise.typechecker.Expanders$$anon$2.expandMacroAnnotations(Expanders.scala:27)
	at org.scalameta.paradise.typechecker.AnalyzerPlugins$MacroPlugin$.pluginsEnterStats(AnalyzerPlugins.scala:46)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.$anonfun$pluginsEnterStats$1(AnalyzerPlugins.scala:450)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterStats(AnalyzerPlugins.scala:449)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterStats$(AnalyzerPlugins.scala:446)
	at org.scalameta.paradise.typechecker.HijackAnalyzer$$anon$2.pluginsEnterStats(HijackAnalyzer.scala:31)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2403)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$98(Typers.scala:5485)
	at scala.tools.nsc.typechecker.Typers$Typer$$Lambda$477/1697211563.apply(Unknown Source)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typerWithLocalContext$1(Typers.scala:491)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:491)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5520)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5527)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5774)
	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2287)
	at scala.tools.nsc.typechecker.ParadiseAnalyzer$ParadiseTyper.typedDefDef(Analyzer.scala:17)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5475)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5526)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5624)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$9(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1987)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1811)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5476)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5526)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5624)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$9(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1987)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1811)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5476)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5526)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5624)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3075)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$9(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3219)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5176)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5479)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5526)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5563)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5593)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5537)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5541)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5620)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:423)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:416)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$Lambda$404/1844511179.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1427)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1412)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1407)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1501)
	at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:44)
	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:124)
	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:131)
	at xsbt.Runner.run(ScaladocInterface.scala:26)
	at xsbt.ScaladocInterface.run(ScaladocInterface.scala:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.doc(AnalyzingCompiler.scala:73)
	at sbt.compiler.AnalyzingCompiler.doc(AnalyzingCompiler.scala:68)
	at sbt.Doc$$anonfun$scaladoc$1.apply(Doc.scala:23)
	at sbt.Doc$$anonfun$scaladoc$1.apply(Doc.scala:23)
	at sbt.RawCompileLike$$anonfun$prepare$1.apply(RawCompileLike.scala:64)
	at sbt.RawCompileLike$$anonfun$prepare$1.apply(RawCompileLike.scala:56)
	at sbt.RawCompileLike$$anonfun$cached$1$$anonfun$2$$anonfun$apply$1.apply(RawCompileLike.scala:49)
	at sbt.RawCompileLike$$anonfun$cached$1$$anonfun$2$$anonfun$apply$1.apply(RawCompileLike.scala:47)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:84)
	at sbt.Tracked$$anonfun$outputChanged$1.apply(Tracked.scala:79)
	at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:54)
	at sbt.RawCompileLike$$anonfun$cached$1.apply(RawCompileLike.scala:39)
	at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:829)
	at sbt.Defaults$$anonfun$docTaskSettings$3.apply(Defaults.scala:807)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by olafurpg** [comment] 2017-07-11 08:03
Duplicate of https://github.com/scalameta/paradise/issues/55 ?

**Comment by xeno-by** [comment] 2017-07-11 16:07
Looks like it.

**Closed by xeno-by** 2017-07-11 16:07 UTC
