### ISSUE TITLE
After transforming, a block should be reparsed as stats

### ISSUE THREAD

**Issue by CremboC** [scalameta/paradise#180] opened 2017-03-08 19:31 UTC
#161 was suppose to fix it, but it still appears to be a problem.

Example:
```scala
import scala.meta._

val source = q"""
  
  def test(): Unit = {
    val d = IWantToBeAClass()
  }
  
  """

val result = source.transform {
  case defn: Defn.Val if defn.syntax.contains("IWantToBeAClass") =>
    q"""
      trait B
      class A extends B
      val d = new A
    """
}
```

Should produce
```scala
  def test(): Unit = {
    trait B
    class A extends B
    val d = new A
  }
```

but actually produces
```scala
  def test(): Unit = {
    {
      trait B
      class A extends B
      val d = new A
    }
  }
```

Tested on paradise `3.0.0-M7` and scalameta `1.6.0`

**Comment by olafurpg** [comment] 2017-03-08 19:59
I think this is working as expected, since you are transforming a term to another term. The only way three statements can be a term is to wrap them in a term.block. It seems you need to flatMap on the stats of the enclosing term.block.

Maybe the transformer can be changed to accommodate expanding a single term to multiple terms, but don't know so much of the Transformer internals.

**Comment by DavidDudson** [comment] 2017-05-28 06:06
Hmm...

So I believe this should be closed as wontfix, here's the issue...

`transform` must return a single `Tree`, which forces it to return a `Term.Block`

## Explanation

### Input

```scala
def test(): Unit = {
  @expander val d = IWantToBeAClass()
}
```

### Output

```scala
def test(): Unit = {
  trait B
  class A extends B
  val d = new A
}
```

Note: This actually should be a nested block.

```scala
def test(): Unit = {
  {
    trait B
    class A extends B
    val d = new A
  }
}
```

The current code is...

```scala
val expandeesArg = expandees.map(_.toMtree[m.Stat]) match {
              case Nil =>
                abort("...")
              case tree :: Nil      => tree
              case list @ _ :: tail => m.Term.Block(list.asInstanceOf[Seq[m.Stat]])
            }
```

Which says the following.

If it is a single term, return that term.
If multiple terms, wrap in a `Term.Block`

Which boils down to this:

If it is a single term that is a `Term.Block` just return it, rather than wrapping.

The moment that you add extra stats to that class, the second block is triggered.

### The issue if we resolve this

Heres some perfectly valid code

```scala

### The main question

Is there an issue with

**Comment by olafurpg** [comment] 2017-05-28 08:30
I agree, this is working as intended.

The macro annotations special case Term.Block to support injecting a companion object. In my opinion, we shouldn't overload Term.Block for that use-case in macro annotations. We should instead type the input/output of macro annotations from `Any => Any` to something `MacroArg => MacroArg` (name up for debate)

```scala
sealed trait MacroArg
case class NoCompanion(defn: Defn) extends MacroArg
case class WithCompanion(defn: Defn, obj: defn.Object) extends MacroArg
// need to support Decl too
```

@CremboC to expand a val into a list of terms, you can match on `Term.Block` or `Template` and flatmap the stats.

**Closed by olafurpg** 2017-05-28 08:30 UTC
