### ISSUE TITLE
Expand macro annotations in REPL

### ISSUE THREAD

**Issue by kralikba** [scalameta/paradise#117] opened 2016-11-04 06:17 UTC
```sbt console``` fails to initialize correctly if the paradise-3.xxx plugin is enabled.
The error message is:
``` [init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/Object.class) ```

A minimal ```build.sbt``` that reproduces the issue:
```sbt
resolvers += Resolver.url( "scalameta-bintray", url("https://dl.bintray.com/scalameta/maven"))(Resolver.ivyStylePatterns)
addCompilerPlugin("org.scalameta" % "paradise" % "3.0.0-M5" cross CrossVersion.full)
scalaVersion := "2.11.8"
libraryDependencies ++= Seq(
        "org.scalameta" %% "scalameta" % "1.1.0"
)
```

**Comment by olafurpg** [comment] 2016-11-04 10:27
Thanks for reporting! Here is a minimal template to reproduce the error: https://github.com/olafurpg/scalameta-macro-template/blob/98d4a69f43f6346abf32ee559a485c3feb9f7e32/build.sbt

```
[master] scalameta-macro-examples: app/console
[info] Starting scala interpreter...
[info]
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_102).
Type in expressions for evaluation. Or try :help.

scala> [init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/rt.jar(java/lang/Object.class)

[init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre/lib/rt.jar(java/lang/Object.class)
null
The compiler did not initialize.
That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
Abandoning crashed session.
```

**Comment by olafurpg** [comment] 2016-11-04 10:38
Here is a diff to fix the issue: https://github.com/olafurpg/scalameta-macro-template/commit/3f5c1e2bc967cd1cac902b5ff69b0c8bf21ab652

Does that work for you?

**Comment by kralikba** [comment] 2016-11-04 12:30
Well, it doesn't throw errors, but I wouldn't say that it works. As the ```paradise``` plugin is not present, the repl is of no use for playing around. (e.g. in ```sbt macros/console```, ```@main object X { println(5) }``` outputs an error message, which I completely understand)

**Comment by olafurpg** [comment] 2016-11-04 12:48
I see what you mean, I haven't used the repl to play around with macro annotations. I just do `~app/run` and hack on the original code. The benefit to this workflow is that you can edit both the macro definition and call-site. The repl is complicated the setup for macros because they need separate compilation.

**Comment by kralikba** [comment] 2016-11-04 12:50
I want to do this only because this works with paradise 2.1.0. If I’m not mistaken, each „line” in the REPL is a separate compilation.

**Comment by olafurpg** [comment] 2016-11-04 12:51
I've updated the issue title, I agree that it would be great to be able to experiment with macro annotations in the REPL.

**Comment by xeno-by** [comment] 2016-11-06 06:07
This is a duplicate of #10. I'll link this very helpful discussion there.

**Closed by xeno-by** 2016-11-06 06:07 UTC
